from pydantic import BaseModel
from typing import Optional, List, Dict, Any


class ChatRequest(BaseModel):
    """
    Single request model for all chat interactions.
    thread_id:            a UUID generated by the frontend when the user opens the chatbot.
                          Send the same thread_id for every message in the same conversation.
    message:              The user's text input. If the frontend injects a language prefix
                          (e.g. "Please reply in Telugu (తెలుగు).\\nUser message: <text>"),
                          the backend automatically strips it and uses only <text>.
    language:             Legacy field — full language name string (e.g. 'hindi', 'telugu').
                          Kept for backward compatibility with the HTML mockup frontend.
    language_code:        ISO 639-1 code (e.g. 'te', 'ta', 'hi', 'ml', 'kn', 'en').
                          Preferred over `language` when sent by the production frontend.
    language_name:        English display name (e.g. 'Telugu').
    language_native_name: Native script name (e.g. 'తెలుగు'). Used directly in LLM prompts.
    """
    thread_id:            str
    message:              str
    language:             Optional[str] = None   # legacy: "hindi", "telugu" etc.
    language_code:        Optional[str] = None   # ISO: "te", "ta", "hi", "ml", "kn", "en"
    language_name:        Optional[str] = None   # "Telugu"
    language_native_name: Optional[str] = None   # "తెలుగు"


class ChatResponse(BaseModel):
    """
    Response from the LangGraph-powered FAQ agent.
    reply:            The bot's text response.
    step:             Current conversation step (start / await_name / chatting / etc.)
    agent:            Which agent produced the reply (grower_agent, corporate_agent, etc.)
                      None during onboarding steps.
    interactive_type: UI component payload instruction ("device" | "app" | None).
    interactive_actions: Server-Driven UI action configurations.
    """
    reply: str
    step:  str
    agent: Optional[str] = None
    interactive_type: Optional[str] = None
    interactive_actions: Optional[List[Dict[str, Any]]] = None
