from pydantic import BaseModel
from typing import Optional


class ChatRequest(BaseModel):
    """
    Single request model for all chat interactions.
    thread_id: a UUID generated by the frontend when the user opens the chatbot.
               Send the same thread_id for every message in the same conversation.
    message:   The user's text input.
    """
    thread_id: str
    message: str


class ChatResponse(BaseModel):
    """
    Response from the LangGraph-powered FAQ agent.
    reply:      The bot's text response.
    step:       Current conversation step (start / await_name / chatting / etc.)
    agent:      Which agent produced the reply (grower_agent, corporate_agent, etc.)
                None during onboarding steps.
    """
    reply: str
    step: str
    agent: Optional[str] = None
